#
# Copyright 2019 Cristian Pozzessere <ilnannyhack(at)gmail(dot)com>
#
# Questo programma è software libero; puoi ridistribuirlo e/o modificarlo
# secondo i termini della Licenza Pubblica Generica GNU (GPL).
#

[theme_info]
name=Nord
description=Dark colors and dishes inspired by the “Nord” color palette
version=1.0.0
author=Cristian Pozzessere < ilnanny >
url=https://github.com/ilnanny75/dotfiles/tree/main/confi/geany/colorschemes/
compat=1.22;1.23;1.23.1;1.24

[named_colors]
# --- Palette Polar Night (Scuri per lo sfondo) ---
nord0=#2E3440
nord1=#3B4252
nord2=#434C5E
nord3=#4C566A

# --- Palette Snow Storm (Chiari per il testo) ---
nord4=#D8DEE9
nord5=#E5E9F0
nord6=#ECEFF4

# --- Palette Frost (Azzurri/Verdi freddi) ---
nord7=#8FBCBB
nord8=#88C0D0
nord9=#81A1C1
nord10=#5E81AC

# --- Palette Aurora (Colori accesi per alert/highlight) ---
nord11=#BF616A
nord12=#D08770
nord13=#EBCB8B
nord14=#A3BE8C
nord15=#B48EAD

[named_styles]
#### Stile Generale dell'Interfaccia
# default: Testo principale (nord6) su sfondo (nord0)
default=nord6;nord0;false;false
error=nord11;;false;false

# Margini e Numeri di riga
margin_line_number=nord3;nord0;false;false
margin_folding=nord2;nord0;false;false
fold_symbol_highlight=nord0

# Selezione e Cursore
selection=0x0;nord2;false;true
current_line=0x0;nord1;true;false
caret=nord4;0x0;false;false
indicator_error=nord11

# Parentesi e Guide
brace_good=nord6;nord10;true;false
brace_bad=nord6;nord11;true;false
indent_guide=nord3;0x0;false;false
white_space=nord3;nord0;true;true

# Marcatori (Marker)
marker_line=nord1;nord1;false;false
marker_search=0x0;nord10;false;false
marker_mark=nord1;nord1;false;false
marker_translucency=1;1;false;false

folding_style=1;1
folding_horiz_line=0;0;false;false

### Linguaggi di Programmazione
# Evidenziazione della Sintassi Generale

# Nota: Colore commento schiarito per Lab 2026 per migliorare la leggibilità
comment=#7B88A1
comment_doc=comment,bold
comment_line=comment
comment_line_doc=comment
comment_doc_keyword=nord10
comment_doc_keyword_error=nord11;;true;true

# Numeri (utilizzano la palette Aurora - Viola/Magenta)
number=nord15
number_1=number
number_2=number

# Tipi di dato, Classi e Funzioni (Palette Frost)
type=nord7
class=type
function=nord8
parameter=function

# Parole Chiave / Keywords (Azzurro Nord)
keyword=nord9
keyword_1=keyword
keyword_2=keyword
keyword_3=keyword
keyword_4=keyword

# Identificatori (utilizzano il colore di default)
identifier=default
identifier_1=identifier
