#!/bin/bash
#================================================
#   O.S.      : Void Linux
#   Author    : Cristian Pozzessere = ilnanny75
#   Github    : https://github.com/ilnanny75
#================================================

# Configura il monitor DVI-0 a 1920x1080
xrandr --newmode "1920x1080_60.00"  108.88  1280 1360 1496 1712  1024 1025 1028 1060 -HSync +Vsync 2>/dev/null || true
xrandr --addmode DVI-0 1920x1080_60.00
xrandr --output DVI-0 --mode 1920x1080_60.00 --primary

echo "Monitor configurato. Fatto!"
sleep 2
