#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
#================================================
# Versione ottimizzata
if ! lsmod | grep -q snd_hda_intel; then
    echo "Caricamento modulo snd_hda_intel..."
    sudo modprobe snd_hda_intel
else
    echo "Il modulo è già caricato."
fi
