#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
#================================================
#================================================
echo "Pulizia utente..."
bleachbit --clean system.tmp # Esempio di flag per non aprire la GUI
echo "Pulizia root..."
sudo bleachbit --clean system.tmp
