#!/bin/bash
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
# ... (Header originale) ...

# Funzione corretta per gestire l'uscita
check_exit_value() {
    if [ $? != 0 ]; then exit 1; fi
}

homefolder=~
input_file=$(zenity --title="Scegli file" --file-selection --filename="$homefolder/")
check_exit_value

expected_checksum=$(zenity --entry --title="Checksum" --text="Inserisci checksum atteso")
check_exit_value

sumtype=$(zenity --title="Tipo" --text="Scegli algoritmo" --list --radiolist \
--column "Scegli" --column "Tipo" TRUE MD5 FALSE SHA1 FALSE SHA256 FALSE SHA512)
check_exit_value

case "$sumtype" in
    MD5) command="md5sum" ;;
    SHA1) command="sha1sum" ;;
    SHA256) command="sha256sum" ;;
    SHA512) command="sha512sum" ;;
esac

# Nota le virgolette "$input_file" per gestire gli spazi
calculated_checksum=$($command "$input_file" | awk '{print $1}')

if [ "$calculated_checksum" == "$expected_checksum" ]; then
    zenity --info --title "Successo!" --text="I checksum corrispondono."
else
    zenity --error --title "Errore!" --text="I checksum NON corrispondono!\n\nCalcolato: $calculated_checksum"
fi
