#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
#================================================

read -p "Inserisci il nome del file ISO o dispositivo (es. /dev/sr0): " INPUT
read -p "Nome file output (es. film.mkv): " OUTPUT

echo "Conversione in corso con codec H.264..."
ffmpeg -i "$INPUT" -c:v libx264 -crf 20 -c:a aac -b:a 192k "$OUTPUT"

exit 0
