#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
#================================================
# Scorciatoia consigliata: Ctrl+Alt+Esc

echo "Clicca sulla finestra che vuoi terminare (Esc per annullare)..."
xkill -id "$(xprop -root -notype | sed -n '/^_NET_ACTIVE_WINDOW/ s/^.*# *\|,.*$//g p')" 2>/dev/null || xkill
