#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
#================================================

echo "Rimozione spazi dai file SVG in corso (ricorsiva)..."

# Trova tutti i file .svg nelle sottocartelle e li rinomina
find . -type f -name "* *.svg" | while read -r file; do
    new_name=$(echo "$file" | sed "s/ //g")
    mv -v "$file" "$new_name"
done

echo "Ridenominazione completata."
exit 0
