#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
#================================================

[[ $(whoami) == 'root' ]] || exec sudo su -c "$0" root

if ! command -v lshw &> /dev/null; then
    echo "Errore: 'lshw' non è installato. Installo..."
    # Qui potresti aggiungere il comando di installazione della tua distro
    exit 1
fi

echo -e "\nDrivers attualmente in uso nel sistema:"
lshw -short | grep -i "driver" || lshw | grep "driver=" | awk -F'driver=' '{print $2}' | awk '{print $1}' | sort -u
