#!/usr/bin/env bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny75    =
#================================================
#================================================

# Verifica se Rofi è installato
if ! command -v rofi &> /dev/null; then
    echo "Errore: Rofi non trovato."
    exit 1
fi

# Lancio del menu principale semplificato
rofi -show drun -theme-str 'configuration { show-icons: true; icon-theme: "Lila_HD"; }' \
     -display-drun "Menu Pro" -p "Esegui:"
