#!/bin/bash
#==========================================================
# ILNANNY ALIAS DEBIAN/MX - Lab 2026
#==========================================================

# --- Gestione Pacchetti ---
alias update='sudo apt update && sudo apt upgrade'
alias install='sudo apt install'
alias instally='sudo apt install -y'
alias remove='sudo apt purge && sudo apt autoremove'
alias search='apt search'
alias show='apt show'

# --- Scorciatoie di Sistema ---
alias sourcelist='sudo geany /etc/apt/sources.list'
alias gosource='thunar /etc/apt/sources.list.d/'

# --- 🚀 ILNANNY LAB 2026 (I tuoi nuovi muscoli) ---
alias pigia='~/dotfiles/scripts/bin/git-push.sh'
alias up='~/dotfiles/scripts/bin/git-up.sh'
alias check='~/dotfiles/scripts/bin/ilnanny-check.sh'
alias cdd='cd ~/dotfiles/bash/etc_bash/bashrc.d/'
alias memo='cat ~/dotfiles/MEMORANDUM.md'
alias vedi='ls -sh --color=auto'
