[files]
recent_files=/home/ilnanny/Scaricati/ilnanny75.github.io/index.html;/media/ilnanny/dati-linux/dotfiles/docs_lab/foxhome_backup.json;/media/ilnanny/dati-linux/header.txt;/home/ilnanny/dotfiles/scripts/bin/ilnanny-postinstall.sh;/home/ilnanny/Scaricati/ilnanny-postinstall.sh;/media/ilnanny/dati-linux/dotfiles/scripts/bin/ilnanny-postinstall.sh;/media/ilnanny/dati-linux/dotfiles/scripts/bin/ilnanny-studio.sh;/media/ilnanny/dati-linux/dotfiles/scripts/bin/ilnanny-vlc-pro.sh;/media/ilnanny/dati-linux/VLC-Arc-Dark/README.md;/home/ilnanny/dotfiles/README.md;
recent_projects=
current_page=0
FILE_NAME_0=0;HTML;0;EUTF-8;1;1;1;%2Fhome%2Filnanny%2FScaricati%2Filnanny75.github.io%2Findex.html;0;4

[project]
session_file=
project_file_path=/home/ilnanny/progetti

[geany]
treeview_position=230
msgwindow_position=1004
geometry=0;0;1920;1048;1;
sidebar_page=0

[VTE]
last_dir=/home/ilnanny

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=405
position_find_y=411
position_replace_x=579
position_replace_y=352
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
