[Appearance]
color_scheme_path=/usr/share/qt5ct/colors/darker.conf
custom_palette=true
icon_theme=Lila_HD
standard_dialogs=gtk3
style=Fusion

[Fonts]
fixed="FiraCode Nerd Font Propo,12,-1,5,57,0,0,0,0,0"
general="FiraCode Nerd Font Propo,12,-1,5,57,0,0,0,0,0"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1200
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\xa8\0\0\0\xb5\0\0\x4\xb9\0\0\x3\xcd\0\0\x1\xaa\0\0\0\xd5\0\0\x4\xb7\0\0\x3\xcb\0\0\0\0\0\0\0\0\a\x80\0\0\x1\xaa\0\0\0\xd5\0\0\x4\xb7\0\0\x3\xcb)

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
